services:
  api-gateway:
    build: ./nginx
    container_name: api-gateway
    ports:
      - "80:80"
    #env_file:
      #- .env
    environment:
      # --- REST ---
      CREATE_USER_HOST: ${CREATE_USER_HOST}
      CREATE_USER_PORT: ${CREATE_USER_PORT}

      DELETE_USER_HOST: ${DELETE_USER_HOST}
      DELETE_USER_PORT: ${DELETE_USER_PORT}

      UPDATE_USER_HOST: ${UPDATE_USER_HOST}
      UPDATE_USER_PORT: ${UPDATE_USER_PORT}

      REGISTER_GAME_HOST: ${REGISTER_GAME_HOST}
      REGISTER_GAME_PORT: ${REGISTER_GAME_PORT}

      # --- GraphQL ---
      GRAPHQL_USER_HOST: ${GRAPHQL_USER_HOST}
      GRAPHQL_USER_PORT: ${GRAPHQL_USER_PORT}

      # --- SOAP: Rol Management ---
      SOAP_CREATE_ROLE_HOST: ${SOAP_CREATE_ROLE_HOST}
      SOAP_CREATE_ROLE_PORT: ${SOAP_CREATE_ROLE_PORT}

      SOAP_DELETE_ROLE_HOST: ${SOAP_DELETE_ROLE_HOST}
      SOAP_DELETE_ROLE_PORT: ${SOAP_DELETE_ROLE_PORT}

      SOAP_UPDATE_ROLE_HOST: ${SOAP_UPDATE_ROLE_HOST}
      SOAP_UPDATE_ROLE_PORT: ${SOAP_UPDATE_ROLE_PORT}

      SOAP_GETBYID_ROLE_HOST: ${SOAP_GETBYID_ROLE_HOST}
      SOAP_GETBYID_ROLE_PORT: ${SOAP_GETBYID_ROLE_PORT}

      SOAP_GETALL_ROLE_HOST: ${SOAP_GETALL_ROLE_HOST}
      SOAP_GETALL_ROLE_PORT: ${SOAP_GETALL_ROLE_PORT}

    restart: unless-stopped
