# Imagen base oficial de Go
FROM golang:1.20-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos go.mod y go.sum primero para aprovechar la cache de dependencias
COPY go.mod ./
RUN go mod download

# Copiamos el resto del proyecto
COPY . .

# Construimos el binario de la aplicación
RUN go build -o main .

# Puerto en el que se ejecutará el microservicio
EXPOSE 3016

# Comando para iniciar el servicio
CMD ["./main"]
