# Etapa 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copiamos el archivo .csproj
COPY RoleManagementService/RoleManagementService.csproj ./RoleManagementService/

# Restauramos dependencias
RUN dotnet restore ./RoleManagementService/RoleManagementService.csproj

# Copiamos el resto del código fuente
COPY RoleManagementService/. ./RoleManagementService/

# Publicamos el proyecto
RUN dotnet publish ./RoleManagementService/RoleManagementService.csproj -c Release -o out

# Etapa 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/out ./
EXPOSE 3019

ENTRYPOINT ["dotnet", "RoleManagementService.dll"]
